-- Franquicia: sucursal Marina Nacional + columnas branch_id + ticket completo.
--
-- Nota de diseño: el prompt original pedía PKs uuid y un modelo de crédito
-- basado en users.credit_balance / customer_id. El esquema real usa PKs
-- bigint en todas partes, y el crédito de empleado YA existe como un motor
-- funcional (employee_consumption + employee_weekly_credit, alimentado por
-- process_sale y usado por la nómina semanal). Por eso:
--   - branches.id es bigint (consistente con el resto del esquema).
--   - No se crea users.credit_balance; se reutiliza el motor de beneficio
--     diario de $100 ya existente vía employees + sale.employee_id.
--   - "Atendió" (quién cobró) no existía como FK; se agrega
--     sales.cashier_user_id -> users(id) para cubrirlo.
--   - Se agregan sales.employee_benefit_before/after para poder reconstruir
--     el crédito antes/después en el ticket sin recalcularlo con datos de
--     "hoy" (que ya no aplicarían si el ticket se reimprime otro día).

CREATE TABLE IF NOT EXISTS public.branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  address text,
  city text,
  phone text,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.branches (name, address, city, phone)
SELECT 'Marina Nacional', 'Marina Nacional 84#', 'Xalapa, Veracruz', '228 355 6350'
WHERE NOT EXISTS (SELECT 1 FROM public.branches WHERE name = 'Marina Nacional');

DO $$
DECLARE
  v_branch_id bigint;
  v_table text;
BEGIN
  SELECT id INTO v_branch_id FROM public.branches WHERE name = 'Marina Nacional' LIMIT 1;

  FOREACH v_table IN ARRAY ARRAY['users','sales','inventory','costs','attendance','promotions','folio_counters']
  LOOP
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = v_table AND column_name = 'branch_id'
    ) THEN
      EXECUTE format(
        'ALTER TABLE public.%I ADD COLUMN branch_id bigint REFERENCES public.branches(id) DEFAULT %s',
        v_table, v_branch_id
      );
    ELSE
      EXECUTE format(
        'ALTER TABLE public.%I ALTER COLUMN branch_id SET DEFAULT %s',
        v_table, v_branch_id
      );
    END IF;

    EXECUTE format('UPDATE public.%I SET branch_id = %s WHERE branch_id IS NULL', v_table, v_branch_id);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_%s_branch_id ON public.%I (branch_id)', v_table, v_table);
  END LOOP;

  -- sales.cashier_user_id: quién cobró (no existía ninguna FK para esto,
  -- solo el texto libre "opened_by").
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'sales' AND column_name = 'cashier_user_id'
  ) THEN
    ALTER TABLE public.sales ADD COLUMN cashier_user_id bigint REFERENCES public.users(id);
    CREATE INDEX idx_sales_cashier_user_id ON public.sales (cashier_user_id);
  END IF;

  -- Snapshot del beneficio diario del empleado al momento de la venta, para
  -- que el ticket pueda mostrar "antes/después" de forma exacta incluso si
  -- se reimprime en otro día.
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'sales' AND column_name = 'employee_benefit_before'
  ) THEN
    ALTER TABLE public.sales ADD COLUMN employee_benefit_before numeric;
    ALTER TABLE public.sales ADD COLUMN employee_benefit_after numeric;
  END IF;
END $$;
